# Generated by Django 4.1.2 on 2022-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(blank=True, to='layout.interest'),
        ),
    ]
