# Generated by Django 4.1.3 on 2022-11-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='text',
        ),
    ]
