# Generated by Django 4.1.3 on 2022-11-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_news_rename_end_time_event_end_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
