# Generated by Django 4.1.2 on 2022-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_alter_event_name_alter_interest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
